wandb_version: 1

activation_function:
  value: tanh
architecture:
  value:
    hidden_layer_size:
    - 256
    - 128
    - 64
    - 10
    num_of_hidden_layers: 4
batch_size:
  value: 64
epochs:
  value: 5
learning_rate:
  value: 0.001
optimizer:
  value: adam
weight_decay:
  value: 0
weight_initialization:
  value: random
