wandb_version: 1

activation_function:
  value: ReLU
architecture:
  value:
    hidden_layer_size:
    - 32
    - 64
    - 10
    num_of_hidden_layers: 3
batch_size:
  value: 32
epochs:
  value: 5
learning_rate:
  value: 0.0001
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_initialization:
  value: xavier
