wandb_version: 1

activation_function:
  value: sigmoid
architecture:
  value:
    hidden_layer_size:
    - 32
    - 64
    - 128
    - 10
    num_of_hidden_layers: 4
batch_size:
  value: 16
epochs:
  value: 5
learning_rate:
  value: 0.001
optimizer:
  value: RMSprop
weight_decay:
  value: 0.0005
weight_initialization:
  value: xavier
