wandb_version: 1

batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 16
learning_rate:
  value: 0.0006
num_of_hidden_layers:
  value: 1
optimizer:
  value: sgd
weight_initialization:
  value: random
