wandb_version: 1

activation_function:
  value: tanh
architecture:
  value:
    hidden_layer_size:
    - 32
    - 64
    - 10
    num_of_hidden_layers: 3
batch_size:
  value: 16
epochs:
  value: 10
learning_rate:
  value: 0.001
optimizer:
  value: RMSprop
weight_decay:
  value: 0.5
weight_initialization:
  value: xavier
