wandb_version: 1

activation_function:
  value: sigmoid
architecture:
  value:
    hidden_layer_size:
    - 32
    - 64
    - 128
    - 356
    - 10
    num_of_hidden_layers: 5
batch_size:
  value: 32
epochs:
  value: 5
learning_rate:
  value: 0.0001
optimizer:
  value: RMSprop
weight_decay:
  value: 0.5
weight_initialization:
  value: xavier
