_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.8
            "8":
                - 5
            "10":
                - 3
            "12": 0.19.8
            "13": linux-x86_64
activation_function:
    value: tanh
architecture:
    value:
        hidden_layer_size:
            - 512
            - 256
            - 128
            - 64
            - 10
        num_of_hidden_layers: 5
batch_size:
    value: 32
epochs:
    value: 5
learning_rate:
    value: 0.0001
optimizer:
    value: nadam
weight_decay:
    value: 0
weight_initialization:
    value: random
