wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.001
num_of_hidden_layers:
  value: 5
optimizer:
  value: Nestrov
weight_decay:
  value: 0
weight_initialization:
  value: random
