wandb_version: 1

activation_function:
  value: ReLU
architecture:
  value:
    hidden_layer_size:
    - 1024
    - 512
    - 256
    - 128
    - 64
    - 10
    num_of_hidden_layers: 6
batch_size:
  value: 64
epochs:
  value: 5
learning_rate:
  value: 0.0001
optimizer:
  value: momentum
weight_decay:
  value: 0.5
weight_initialization:
  value: random
