_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 5
hidden_layer_size:
    value: 10
learning_rate:
    value: 0.0006
num_of_hidden_layers:
    value: 2
optimizer:
    value: nesterov
weight_initialization:
    value: xavier
