wandb_version: 1

activation_function:
  value: sigmoid
architecture:
  value:
    hidden_layer_size:
    - 256
    - 128
    - 64
    - 10
    num_of_hidden_layers: 4
batch_size:
  value: 32
epochs:
  value: 10
learning_rate:
  value: 0.001
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_initialization:
  value: random
