wandb_version: 1

activation_function:
  value: ReLU
architecture:
  value:
    hidden_layer_size:
    - 1024
    - 512
    - 256
    - 128
    - 64
    - 10
    num_of_hidden_layers: 6
batch_size:
  value: 16
epochs:
  value: 5
learning_rate:
  value: 0.001
optimizer:
  value: RMSprop
weight_decay:
  value: 0
weight_initialization:
  value: xavier
