wandb_version: 1

activation_function:
  value: ReLU
batch_size:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.0001
num_of_hidden_layers:
  value: 3
optimizer:
  value: Adam
weight_decay:
  value: 0.5
weight_initialization:
  value: random
