wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 64
learning_rate:
  value: 0.0001
num_of_hidden_layers:
  value: 5
optimizer:
  value: Nadam
weight_decay:
  value: 0.5
weight_initialization:
  value: Xavier
