wandb_version: 1

batch_size:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.0003
num_of_hidden_layers:
  value: 2
optimizer:
  value: adam
weight_initialization:
  value: xavier
