wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.0001
num_of_hidden_layers:
  value: 5
optimizer:
  value: RMSprop
weight_decay:
  value: 0.5
weight_initialization:
  value: random
