wandb_version: 1

activation_function:
  value: tanh
architecture:
  value:
    hidden_layer_size:
    - 512
    - 256
    - 128
    - 64
    - 10
    num_of_hidden_layers: 4
batch_size:
  value: 16
epochs:
  value: 10
learning_rate:
  value: 0.0005
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_initialization:
  value: random
