wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 128
learning_rate:
  value: 0.0001
num_of_hidden_layers:
  value: 3
optimizer:
  value: Adam
weight_decay:
  value: 0
weight_initialization:
  value: random
