wandb_version: 1

batch_size:
  value: 64
epochs:
  value: 5
hidden_layer_size:
  value:
  - 128
  - 64
  - 32
  - 10
learning_rate:
  value: 0.0001
num_of_hidden_layers:
  value: 4
optimizer:
  value: nesterov
weight_initialization:
  value: random
