wandb_version: 1

batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value:
  - 128
  - 64
  - 32
  - 10
learning_rate:
  value: 0.0003
num_of_hidden_layers:
  value: 4
optimizer:
  value: momentum
weight_initialization:
  value: random
