wandb_version: 1

batch_size:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value:
  - 128
  - 64
  - 32
  - 10
learning_rate:
  value: 0.0005
num_of_hidden_layers:
  value: 4
optimizer:
  value: adam
weight_initialization:
  value: xavier
