wandb_version: 1

activation_function:
  value: ReLU
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.001
num_of_hidden_layers:
  value: 4
optimizer:
  value: Nadam
weight_decay:
  value: 0.5
weight_initialization:
  value: Xavier
