wandb_version: 1

activation_function:
  value: ReLU
batch_size:
  value: 64
epochs:
  value: 25
hidden_layer_size:
  value: 128
learning_rate:
  value: 0.0003
num_of_hidden_layers:
  value: 4
optimizer:
  value: Adam
weight_decay:
  value: 0.0005
weight_initialization:
  value: Xavier
