wandb_version: 1

activation_function:
  value: sigmoid
architecture:
  value:
    hidden_layer_size:
    - 128
    - 64
    - 10
    num_of_hidden_layers: 3
batch_size:
  value: 32
epochs:
  value: 10
learning_rate:
  value: 0.0001
optimizer:
  value: nesterov
weight_decay:
  value: 0
weight_initialization:
  value: xavier
