wandb_version: 1

activation_function:
  value: tanh
architecture:
  value:
    hidden_layer_size:
    - 512
    - 256
    - 128
    - 64
    - 10
    num_of_hidden_layers: 5
batch_size:
  value: 32
epochs:
  value: 5
learning_rate:
  value: 0.0001
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_initialization:
  value: random
